### ISSUE TITLE
Doesn't Zoom at all

### ISSUE THREAD

**Issue by redmunds** [thomasvalera/Brackets-CodeOverview#3]
I tried this extension on both Win7 and Mac 10.8 with same results.
- Overview, is displayed at 100% with slider in middle
- Slider doesn't do anything, even if I switch docs
- [-] and [+] don't do anything. Cursor shows I-bar on mouseover

Note that I am running cloned version with latest master, so this could be something that was introduced after current version (Sprint 36) was released. If so, that'll give you a head's up before 37 is released :)

**Comment by mbarwick83** [comment]
This exact issue highlighted above still exists for me. Installed directly from extension manager. On Macbook retina (maybe that's an issue?). Help?

**Comment by jelofsson** [comment]
I can confirm that the zoom isn't working on my Macbook OSX Yosemite.
